### ISSUE TITLE
im.value_at_coords() broken for MultiBandRaster 

### ISSUE THREAD

**Issue by grossular** [GeoUtils/georaster#10]
> \>\>\> import georaster
> \>\>\> im = georaster.MultiBandRaster('geo.tif')
> \>\>\> im.value_at_coords(57.6,10.6)
>Traceback (most recent call last):
>    File "/usr/local/lib/python2.7/site-packages/georaster/georaster.py", line 661, in value_at_coords
>    val = format_value(data)
>UnboundLocalError: local variable 'data' referenced before assignment`

Issue can be fixed with

    @656,1
    # Deal with MultiBandRaster case
        else:   
            value = {}
            +win = {}
        for b in range(1,self.ds.RasterCount+1):
            -d = self.ds.GetRasterBand(b).ReadAsArray(xpx,ypx,xo,yo)
            +data = self.ds.GetRasterBand(b).ReadAsArray(xpx,ypx,xo,yo)
            val = format_value(data)
            # Store according to GDAL band numbers
            value[b] = val
            win[b] = data

**Comment by atedstone** [comment]
This issue has been fixed as of release ﻿00d0300a38c5d8564ebfc37b828bfb83c8e0d6be.
