### ISSUE TITLE
Comparison to RasterIO

### ISSUE THREAD

**Issue by fmaussion** [GeoUtils/georaster#12]
This looks like a nice package! Out of curiosity, how does it compare to or complements [rasterio](https://github.com/mapbox/rasterio)? I think a short paragraph in the README or the docs would help newcomers like me to place the package in context.

**Comment by atedstone** [comment]
Nice idea, thanks for this. I'll have to do some digging on rasterio's capabilities - when we started to develop georaster in 2014 rasterio was in a very early state of development and I've not really re-visited it since as I can generally get what I need done with georaster.

**Comment by adehecq** [comment]
Hi Fabien,

Welcome to georaster ! As Andrew mentioned, this repo was the fusion of different tools that Andrew and I both developed on our side at a time when not many high-level libraries existed to handle raster/vector files. Probably some good solutions exist nowadays, but so far I’ve been really used to our custom tools that I only use this.
I hope you’ll find it useful and collaborate on it. We also had a plan to merge georaster and geovector into one repo Geoutils at some point but haven’t really done it. But if you work with shapefile, you should have a look at geovector too: https://github.com/GeoUtils/geoutils/tree/master/geoutils
I once created a small doc that I never put online, I hope to do that at some point, but I can send it to you if you want to be a beta tester.

Amaury

P.S: I “stole” your website design a couple months ago. I still have a lot to learn, but I hope to personalize it a bit more: https://adehecq.github.io/ Thanks for sharing!


On Apr 2, 2019, at 15:00, Fabien Maussion <notifications@github.com<mailto:notifications@github.com>> wrote:


This looks like a nice package! Out of curiosity, how does it compare to or complements rasterio<https://github.com/mapbox/rasterio>? I think a short paragraph in the README or the docs would help newcomers like me to place the package in context.

**Comment by fmaussion** [comment]
>  when we started to develop georaster in 2014 rasterio was in a very early state of development and I've not really re-visited it since as I can generally get what I need done with georaster.

Yes, this is often how it goes. I have the same feeling with my small salem library. We use rasterio intensively now (and added a backend for [xarray](http://xarray.pydata.org/en/stable/generated/xarray.open_rasterio.html) recently), and your library seemed very similar so I got curious!

> I “stole” your website design a couple months ago.

Nice website! And good that your google scholar icon on the landing page still points to mine :wink:. The design comes from an earlier version of minimal mistakes anyway, it's not mine!

**Comment by adehecq** [comment]
On Apr 5, 2019, at 17:53, Fabien Maussion <notifications@github.com<mailto:notifications@github.com>> wrote:


when we started to develop georaster in 2014 rasterio was in a very early state of development and I've not really re-visited it since as I can generally get what I need done with georaster.

Yes, this is often how it goes. I have the same feeling with my small salem library. We use rasterio intensively now (and added a backend for xarray<http://xarray.pydata.org/en/stable/generated/xarray.open_rasterio.html> recently), and your library seemed very similar so I got curious!

I’ll check your library too then !


I “stole” your website design a couple months ago.

Nice website! And good that your google scholar icon on the landing page still points to mine 😉. The design comes from an earlier version of minimal mistakes anyway, it's not mine!

What do you mean? I tried all the Google scholar links and they all point to mine…
Oh ok it was an earlier version. I didn’t really like the last one.

**Comment by fmaussion** [comment]
> What do you mean? 

For me the link below your bio and image (the scholar logo) still points to mine

**Comment by adehecq** [comment]
Strange… Mine point to https://scholar.google.com/citations?user=/4Fk2yxUAAAAJ
What’s your link?


On Apr 7, 2019, at 13:11, Fabien Maussion <notifications@github.com<mailto:notifications@github.com>> wrote:


For me the link below your bio and image (the scholar logo) still points to mine

**Comment by fmaussion** [comment]
haha it seems this is a general link, neither working for you or for me ;-) - try to open it in a private browser instead and you'll see

(sorry @atedstone for the unrelated noise here ;)

**Comment by adehecq** [comment]
I got it ! There’s an extra slash in the author-bio code that causes it to fail… And of course as long as I'm logged in, it points to my profile (yours when you try it)…
Should be fixed now.

@atedstone, it’s better for you too, as my top paper is still yours! ;-)


On Apr 7, 2019, at 13:17, Fabien Maussion <notifications@github.com<mailto:notifications@github.com>> wrote:


haha it seems this is a general link, neither working for you or for me ;-) - try to open it in a private browser instead and you'll see

(sorry @atedstone<https://github.com/atedstone> for the unrelated noise here ;)

**Comment by atedstone** [comment]
Very short note added to readme indicating that rasterio now exists and is a good choice for most tasks. Noted that this package is now more in state of maintenance than development (focus on supporting existing applications/bugfixes).
