### ISSUE TITLE
Put package requirements in setup.py

### ISSUE THREAD

**Issue by CarliJoy** [GeoUtils/georaster#19]
Unfortunaetly the `setup.py` does not state the requirements.
So once you install the package in a virtual environment you have to manually figure them out.

Best to figure them out is to create a new virtualenvironment and do some tests.
If i have some time I might do a PR.

In general I am a bit confused as the documentation link https://georaster.readthedocs.io/en/latest/api.html "edit on github" is not pointing to this repro but to https://github.com/atedstone/georaster/blob/master/docs/api.rst which repro is the most current one?

**Comment by CarliJoy** [comment]
@atedstone are you also editing the repro?

**Comment by adehecq** [comment]
Hi,

Thanks for the feedback. It would indeed be interesting to add this. @atedstone, you might know better but let me know if you want me to add this.
Alternatively, the requirements are stated in the conda requirement file here: https://github.com/GeoUtils/georaster/blob/master/docs/rtd_environment.yml 

Regarding the repositories issue, both Andrew and I have our fork of the package, but the one in GeoUtils is meant to be the stable version. So you're right, the documentation should point to GeoUtils, not Andrew's own. 
@atedstone, I guess you're the only one who can make the change?

**Comment by atedstone** [comment]
@CarliJoy thanks for spotting this, I'll update the documentation link asap. The version on GeoUtils is indeed the stable version and is the only place where we periodically releases.

@adehecq would you mind looking at the requirements for virtualenv installation?

We've prioritised packaging for conda-forge so far, so the package requirements are sorted here - @adehecq take a look at https://github.com/conda-forge/georaster-feedstock/blob/master/recipe/meta.yaml which should help to improve our setup.py.

**Comment by atedstone** [comment]
> Unfortunaetly the `setup.py` does not state the requirements.
> So once you install the package in a virtual environment you have to manually figure them out.

There is now a requirements.txt file.

However, due to the complexities of GDAL installations (which I don't believe that a requirements.txt file can solve), we still recommend that georaster is installed from conda-forge.

> 
> Best to figure them out is to create a new virtualenvironment and do some tests.
> If i have some time I might do a PR.
> 
> In general I am a bit confused as the documentation link https://georaster.readthedocs.io/en/latest/api.html "edit on github" is not pointing to this repro but to https://github.com/atedstone/georaster/blob/master/docs/api.rst which repro is the most current one?

The link is now fixed.
